purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0
  brandStrength: 0.4817401
  lightness: 1
  brandColors:
    - '#FFFFFF'
    - '#DD41FF'
    - '#000000'
    - '#9000FF'
    - '#FF8FFF'
  rhythmicContrast: 0
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
cta:
  bucket: null
  version: null
  domain: null
name: DavidSights
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.4828142
layout_spectrum: 0
