layout_spectrum: 0.2991407
typography_spectrum: 0.4129968
color:
  saturation: 0.6723405
  lightness: 0.7674767
  brandStrength: 0.247935
  rhythmicContrast: 0.414297
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
name: DavidSights
